
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      my-metadata: 自定义元数据
server:
  port: 8003
spring:
  application:
    name: provider-user-metadata